UET CSE/UET CSE/Models/AchievementViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace UET_CSE.Models
{
    public class AchievementViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Achievement Date")]
        public System.DateTime Achievement_Date { get; set; }
        [Required]
        public string Achievement { get; set; }
        [Required]
        public string Email { get; set; }
        
        public string ImagePath { get; set; }
        [Required]
        [Display(Name ="Image File")]
        public HttpPostedFileBase ImageFile { get; set; }


    }
}

UET CSE/UET CSE/Models/AnnouncementViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace UET_CSE.Models
{
    public class AnnouncementViewModel
    {
        [Required]
        public string Topic { get; set; }

        [Required]
        public string Description { get; set; }
    }
}

UET CSE/UET CSE/Models/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UET_CSE.Models
{
    public class EventViewModel
    {
        [Required]
        [Display(Name = "Event Name")]
        public string Event_Name { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Start Date")]
        public System.DateTime Start_Date { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "End Date")]
        public System.DateTime End_Date { get; set; }
        [Required]
        [Display(Name ="Event Time")]
        [DataType(DataType.Time)]
        public TimeSpan Event_Time { get; set; }
        [Required]
        [Display(Name = "Ticket Price")]
        [RegularExpression("[0-9]+", ErrorMessage ="Ticket Price must be in numbers")]
        public string Ticket_Price { get; set; }
        [Required]
        public string Place { get; set; }
        
        public string ImagePath { get; set; }
        [Required]
        [Display(Name ="Image File")]
        public HttpPostedFileBase ImageFile { get; set; }
    }
}

UET CSE/UET CSE/Models/FacultyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace UET_CSE.Models
{
    public class FacultyViewModel
    {
        public int Id { get; set; }
        [Required]
        [RegularExpression(@"^(([A-Z][a-z]+[\s]{1}[A-za-z]+)|([A-Z][a-z]+))$", ErrorMessage = "Name must be valid alphabets")]
        public string Name { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        
        public string ImagePath { get; set; }
        [Required]
        [Display(Name ="Image File")]
        public HttpPostedFileBase ImageFile { get; set; }
        [Required]
        public string Deisgnation { get; set; }
        [Required]
        public string Qualification { get; set; }
        [Required]
        [Display(Name = "Other Qualification")]
        public string Other_Qualification { get; set; }
        [Required]
        public string Gender { get; set; }
    }
}

UET CSE/UET CSE/Controllers/VisitorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UET_CSE.Models;
using System.IO;

namespace UET_CSE.Controllers
{
    public class VisitorController : Controller
    {
        // GET: Visitor
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult HomePage()
        {
            ViewBag.Title = "WE ENSURE BETTER EDUCATION FOR A BETTER WORLD";
            ViewBag.Info = "Computer science is the theory, experimentation, and engineering that form the basis for the design and use of computers. It involves the study of algorithms that process, store, and communicate digital information.";

            UETCSEDbEntities db = new UETCSEDbEntities();
            ViewBag.Events = db.AddEvents;
            ViewBag.Faculty = db.AddFaculties;
            ViewBag.Achievements = db.AddAchievements;
            ViewBag.Announcements = db.AddAnnouncements;
            ViewBag.Academics = db.AddAcademics;
            return View();

        }
        public ActionResult about()
        {
            ViewBag.Title = "About";
            return View();
        }

        public ActionResult Events()
        {
            ViewBag.Title = "Events";
            UETCSEDbEntities db = new UETCSEDbEntities();
            return View(db.AddEvents);
        }

        public ActionResult EventsDetail(int? Name)
        {
            return View();
        }

        public ActionResult Faculty()
        {
            ViewBag.Title = "Faculty";
            UETCSEDbEntities db = new UETCSEDbEntities();
            List<AddFaculty> EventList = db.AddFaculties.ToList();

            
            return View(db.AddFaculties);
        }

        public ActionResult FacultyDetail(int id)
        {
            ViewBag.Title = "Faculty Detail";
            using (UETCSEDbEntities db = new UETCSEDbEntities())
            {
              return View(db.AddFaculties.Where(x => x.Id == id).Single());
            }
        }
        [HttpPost]
        public ActionResult FacultyDetail(AddFaculty obj, int id)
        {
            try
            {
                using (UETCSEDbEntities db = new UETCSEDbEntities())
                {
                    db.AddFaculties.Find(id).Name = obj.Name;
                    db.AddFaculties.Find(id).Email = obj.Email;
                    db.AddFaculties.Find(id).Designation = obj.Designation;
                    db.AddFaculties.Find(id).Qualification = obj.Qualification;
                    db.AddFaculties.Find(id).Other_Qualification = obj.Other_Qualification;
                    db.AddFaculties.Find(id).Gender = obj.Gender;
                    ViewBag.Image = Server.MapPath("~") + db.AddFaculties.Find(id).ImagePath;
                    db.AddFaculties.Find(id).ImagePath = obj.ImagePath;
                    db.SaveChanges();
                }
                    return View("HomePage");
            }
            catch
            {
                return View();
            }
            
        }


        public ActionResult Achievement()
        {
            ViewBag.Title = "Achievements";
            UETCSEDbEntities db = new UETCSEDbEntities();
            return View(db.AddAchievements);
        }


        public ActionResult Announcement()
        {
            ViewBag.Title = "Announcements";
            UETCSEDbEntities db = new UETCSEDbEntities();
            return View(db.AddAnnouncements);
        }
        
        // GET: Visitor/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Visitor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Visitor/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Visitor/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Visitor/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Visitor/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Visitor/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UET CSE/UET CSE/Views/Visitor/Achievement.cshtml
@model IEnumerable<UET_CSE.Models.AddAchievement>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="events-list-area section-gap event-page-lists">
    <div class="container">
        <div class="row align-items-center">
            @foreach (var item in Model)
            {
                <div class="col-lg-6 pb-30">
                    <div class="single-carusel row align-items-center">
                        <div class="col-12 col-md-6 thumb">
                            <img class="img-fluid" src="@Url.Content(item.Image_Path)" alt="" style="width:263px;height:200px;">
                        </div>
                        <div class="detials col-12 col-md-6">
                            <h4>
                                @item.Achievement
                            </h4>
                            <p>
                                Name: @item.Name
                                <br />
                                Email: @item.Email
                            </p>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</section>

UET CSE/UET CSE/Views/Visitor/Announcement.cshtml
@model IEnumerable<UET_CSE.Models.AddAnnouncement>

@{
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<section class="events-list-area section-gap event-page-lists">
    <div class="container">
        <div class="row align-items-center">
            @foreach (var item in Model)
            {
                <div class="col-lg-6 pb-30">
                    <div class="single-carusel row align-items-center">
                       
                        <div class="detials col-12 col-md-6">
                            <h4>
                                @item.Topic
                            </h4>
                            <p>
                                @item.Description
                            </p>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</section>

UET CSE/UET CSE/Views/Visitor/Events.cshtml
@model IEnumerable<UET_CSE.Models.AddEvent>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="events-list-area section-gap event-page-lists">
    <div class="container">
        <div class="row align-items-center">
            @foreach (var item in Model)
            {
                <div class="col-lg-6 pb-30">
                    <div class="single-carusel row align-items-center">
                        <div class="col-12 col-md-6 thumb">
                            <img class="img-fluid" src="@Url.Content(item.ImagePath)" alt="">
                        </div>
                        <div class="detials col-12 col-md-6">
                            <p>@item.Start_Date - @item.End_Date</p>

                            <h4>
                                @item.Event_Name
                            </h4>
                            <p>
                                @item.Description

                            </p>
                        </div>
                    </div>

                </div>
            }
        </div>
    </div>
</section>

UET CSE/UET CSE/Views/Visitor/EventsDetail.cshtml
@model UET_CSE.Models.AddEvent
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="event-details-area section-gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 event-details-left">
                <div class="main-img">
                    <img class="img-fluid" src="@Url.Content(Model.ImagePath)" alt="">
                </div>
                <div class="details-content">
                    <div class="section-top-border">
                        <h3 class="mb-30">
                            <dl>
                                <dd>
                                    @Html.DisplayFor(model => model.Event_Name)
                                </dd>
                            </dl>
                           
                        </h3>
                        
                        <div class="row">
                            <div class="col-lg-12">
                                <blockquote class="generic-blockquote">
                                    @Html.DisplayFor(model => model.Description)
                                </blockquote>
                            </div>
                        </div>
                    </div>
                </div>
   @*             <div class="social-nav row no-gutters">
                    <div class="col-lg-6 col-md-6 navs">
                        <a href="#" class="nav-prev"><span class="lnr lnr-arrow-left"></span>Prev Event</a>
                        <a href="#" class="nav-next">Next Event<span class="lnr lnr-arrow-right"></span></a>
                    </div>
                </div>*@
            </div>
            <div class="col-lg-4 event-details-right">
                <div class="single-event-details">
                    <h4>Details</h4>
                    <ul class="mt-10">
                        <li class="justify-content-between d-flex">
                            <span>Start date</span>
                            <span>
                            @Html.DisplayFor(model => model.Start_Date)
                            </span>
                        </li>
                        <li class="justify-content-between d-flex">
                            <span>End date</span>
                            <span>
                            @Html.DisplayFor(model => model.End_Date)
                           </span>
                        </li>
                        <li class="justify-content-between d-flex">
                            <span>Ticket Price</span>
                            <span>@Html.DisplayFor(model => model.Ticket_Price)</span>
                        </li>
                    </ul>
                </div>
                <div class="single-event-details">
                    <h4>Venue</h4>
                    <ul class="mt-10">
                        <li class="justify-content-between d-flex">
                            <span>Place</span>
                            <span>@Html.DisplayFor(model => model.Place)</span>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

UET CSE/UET CSE/Views/Visitor/Faculty.cshtml
@model IEnumerable<UET_CSE.Models.AddFaculty>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="popular-courses-area section-gap courses-page">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="single-popular-carusel col-lg-3 col-md-6">
                    <div class="thumb-wrap relative">
                        <div class="thumb relative">
                            <div class="overlay overlay-bg"></div>
                            <img class="img-fluid" src="@Url.Content(item.ImagePath)" alt="">
                        </div>
                    </div>
                    <div class="details">
                        <h4>
                            @item.Name
                        </h4>
                        <p>
                            Designation : @item.Designation
                            <br />
                            Qualification : @item.Qualification
                        </p>
                    </div>
                </div>
            }



        </div>
    </div>
</section>

UET CSE/UET CSE/Views/Visitor/FacultyDetail.cshtml
@model UET_CSE.Models.AddFaculty
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("FacultyDetail", "Visitor", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    <section class="course-details-area pt-120">
        <div class="container">
            <div class="row">

                <div class="col-lg-8 left-co ntents">
                    <hr />
                    <div class="main-image">
                        @* <img class="img-fluid" src="@Url.Content(@ViewBag.Image)" alt="">
                        *@
                    </div>
                    <div class="jq-tab-wrapper" id="horizontalTab">
                    </div>
                </div>
                <div class="col-lg-4 right-contents">
                    <ul>
                        <li>
                            <a class="justify-content-between d-flex" href="#">
                                <p>Teacher Name</p>
                                <span class="or">@Html.EditorFor(model => model.Name)</span>
                            </a>
                        </li>
                        <li>
                            <a class="justify-content-between d-flex" href="#">
                                <p>Designation</p>
                                <span> @Html.EditorFor(model => model.Designation)</span>
                            </a>
                        </li>
                        <li>
                            <a class="justify-content-between d-flex" href="#">
                                <p>Qualification </p>
                                <span>@Html.EditorFor(model => model.Qualification)</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
}

UET CSE/UET CSE/Views/Visitor/HomePage.cshtml
@{
    Layout = "~/Views/Shared/HomePageLayout.cshtml";
}

<section class="popular-course-area section-gap">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-70 col-lg-8">
                <div class="title text-center">
                    <h1 class="mb-10"> <p id="Courses">We Ensure Your Best Future</h1></p>
                    <!--                        @*<p>There is a moment in the life of any aspiring.</p>*@ -->
                </div>
            </div>
        </div>
        <div class="row">
            <div class="active-popular-carusel">
                @foreach (var item in ViewBag.Academics)
                {
                    <div class="single-popular-carusel">
                        <div class="thumb-wrap relative">
                            <div class="thumb relative">
                                <div class="overlay overlay-bg"></div>
                                <img class="img-fluid" src="@Url.Content(@item.ImagePath ) " alt="" style="width:263px;height:200px;">
                            </div>
                            <div class="meta d-flex justify-content-between">
                                <br>
                            </div>
                        </div>
                        <div class="details">
                            <a href="#">
                                <h4>
                                    @item.Degree_Program
                                </h4>

                            </a>
                            <p>
                                @item.Description
                            </p>
                        </div>
                    </div>
                }
                
                
                
            </div>
        </div>
    </div>
</section>
<!-- Start upcoming-event Area -->
<section class="upcoming-event-area section-gap">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-70 col-lg-8">
                <div class="title text-center">

                    <h1 class="mb-10"> <p id="Events"> Upcoming Events of UET CSE</h1></p>
                    <p>
                        Upcoming Events of the department of CSE, Uet Lahore <a href="http://localhost:11751/Visitor/Events" class="genric-btn primary small" style="background-color:rgba(4,9,30,0.9)">Events</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="active-upcoming-event-carusel">
                @{
                    foreach (var item in ViewBag.Events)
                    {
                        <div class="single-carusel row align-items-center">
                            <div class="col-12 col-md-6 thumb">
                                <img class="img-fluid" src="@Url.Content(@item.ImagePath)" style="width:263px;height:200px;">
                            </div>
                            <div class="detials col-12 col-md-6">
                                <p>@item.Start_Date - @item.End_Date</p>
                                <a href="http://localhost:11751/Visitor/EventsDetail">
                                    <h4>
                                        @item.Event_Name
                                    </h4>
                                </a>
                                <p>
                                    @item.Description
                                </p>
                            </div>
                        </div>
                    }
                }
                
                
</section>
<!-- End upcoming-event Area -->
<!-- Start Achievement Section-->
<section class="popular-course-area section-gap">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-70 col-lg-8">
                <div class="title text-center">
                    <h1 class="mb-10"> <p id="Faculty">Faculty</p></h1>
                    <p>Faculty of CSE Department,UET Lahore <a href="http://localhost:11751/Visitor/Faculty" class="genric-btn primary small" style="background-color:rgba(4,9,30,0.9)">Faculty</a>

                </div>
            </div>
        </div>
        <div class="row">
            <div class="active-popular-carusel">
                @foreach (var item in ViewBag.Faculty)
                {
                    <div class="single-popular-carusel">
                        <div class="thumb-wrap relative">
                            <div class="thumb relative">
                                <div class="overlay overlay-bg"></div>
                                <img class="img-fluid" src="@Url.Content(@item.ImagePath)" alt="" style="width:263px;height:200px;">
                            </div>
                            <div class="meta d-flex justify-content-between">
                                <!--                @*  <p><span class="lnr lnr-users"></span>  <span @*class="lnr lnr-bubble"></span></p>*@
                                       -->
                                <br>
                            </div>
                        </div>
                        <div class="details">
                           
                            <h4>

                            @item.Name
                                <!--@Html.ActionLink((string)item.Name, "FacultyDetail", "Visitor", new { id = item.Id })
                            --></h4>
                            <p>
                                Designation : @item.Designation
                                <br />
                                Qualification : @item.Qualification
                                <br />
                            </p>
                        </div>
                    </div>
                }
                

            </div>
        </div>
</section>
<!-- End Faculty Section -->
<!-- Start Achievement Section-->
<section class="upcoming-event-area section-gap">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-70 col-lg-8">
                <div class="title text-center">

                    <h1 class="mb-10"> <p id="Achievements"> Achievements</h1></p>
                    <p>Achievements of CSE Department, UET Lahore     <a href="http://localhost:11751/Visitor/Achievement" class="genric-btn primary small" style="background-color:rgba(4,9,30,0.9)">Achievements</a>

                </div>
            </div>
        </div>
        <div class="row">
            <div class="active-upcoming-event-carusel">
                @foreach (var item in ViewBag.Achievements)
                {
                    <div class="single-carusel row align-items-center">
                        <div class="col-12 col-md-6 thumb">
                            <img class="img-fluid" src="@Url.Content(@item.Image_Path)" alt="" style="width:263px;height:200px;">
                        </div>
                        <div class="detials col-12 col-md-6">
                            <h4>
                                @Html.ActionLink((string)item.Name, "Achievement", "Visitor", new { @style = "font-weight:bold" })
                            </h4>
                                <p>
                                @item.Achievement
                                <br />
                                Name: @item.Name
                                <br />
                                Email: @item.Email<br>
                            </p>
                        </div>
                    </div>
                }               
            </div>
        </div>
</section>


<section class="upcoming-event-area section-gap">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-70 col-lg-8">
                <div class="title text-center">

                    <h1 class="mb-10"> <p id="Announcements"> Announcements</h1></p>
                    
                </div>
            </div>
        </div>
        <div class="row">
            <div class="active-upcoming-event-carusel">
                @{
                    foreach (var item in ViewBag.Announcements)
                    {
                        <div class="single-carusel row align-items-center">
                           
                            <div class="detials col-12 col-md-6">
                                <h4>
                                    @item.Topic
                                </h4>

                                <p>
                                    @item.Description
                                </p>
                            </div>
                        </div>
                    }
                }


</section>

UET CSE/UET CSE/Views/Visitor/about.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="event-details-area section-gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 event-details-left">
                <div class="details-content">
                    <div class="section-top-border">
                        <h3 class="mb-30">About Computer Science and Engineering Department, UET Lahore</h3>
                        <div class="row">
                            <div class="col-lg-12">
                                <blockquote class="generic-blockquote">
                                    University of Engineering and Technology Lahore established a Computer Center. This center was equipped with a contemporary IBM 1130 third generation computer that batch processed submitted jobs. The computer was equipped with a disk and a monitor. The center was responsible for planning and teaching courses in Computer Science and Numerical Analysis, which formed an integral part of the curricula for all disciplines of B.Sc. Engineering degree in the university. The center also offered short term computer courses for other private and public sector organizations. In 1978, it started offering a Masters Degree program in Computer Science, thus becoming the first center in the country to offer Computer Science degree.
                                    The department holds an endowment chair given by His Majesty Sultan Qaboos Bin Said-Al-Said, Sultan of Oman
                                </blockquote>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>